version: '3'
services:
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
    - 5432:5432
  cache:
    image: redis:4
    ports:
    - 6379:6379
